// GENERATED by npm run bundle:scan — DO NOT EDIT.
// Source: supabase/functions/telegram-scan/handler.src.ts + src/cron/manualScan.ts
// (same deterministic engine as the 24/7 cron, bundled — never duplicated).

// src/market/hyperliquid/types.ts
var HyperliquidError = class extends Error {
  kind;
  retryable;
  constructor(kind, message, retryable = true) {
    super(message);
    this.name = "HyperliquidError";
    this.kind = kind;
    this.retryable = retryable;
  }
};

// src/market/diagnostics.ts
var counters = {
  restRequests: 0,
  restTimestamps: [],
  wsConnections: 0,
  wsPeakConnections: 0,
  cacheHits: 0,
  cacheMisses: 0,
  rateLimits: 0,
  activeSubscriptions: 0
};
var MAX_TIMESTAMPS = 5e3;
function recordRestRequest(now = Date.now()) {
  counters.restRequests += 1;
  counters.restTimestamps.push(now);
  if (counters.restTimestamps.length > MAX_TIMESTAMPS) {
    counters.restTimestamps.splice(0, counters.restTimestamps.length - MAX_TIMESTAMPS);
  }
}
function recordRateLimit() {
  counters.rateLimits += 1;
}
function recordCacheHit() {
  counters.cacheHits += 1;
}
function recordCacheMiss() {
  counters.cacheMisses += 1;
}

// src/market/hyperliquid/client.ts
var INFO_URL = "https://api.hyperliquid.xyz/info";
var DEFAULT_TIMEOUT_MS = 12e3;
function isRateLimitStatus(status) {
  return status === 429;
}
function errorMessageForStatus(status, bodyText) {
  if (status === 429)
    return "Hyperliquid rate limit hit. Retrying with backoff\u2026";
  if (status >= 500)
    return "Unable to retrieve Hyperliquid market data. Retrying\u2026";
  return `Hyperliquid request failed (HTTP ${status}). ${bodyText.slice(0, 160)}`;
}
async function postInfo(body, opts) {
  const timeoutMs = opts?.timeoutMs ?? DEFAULT_TIMEOUT_MS;
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  const onAbort = () => controller.abort();
  opts?.signal?.addEventListener("abort", onAbort, { once: true });
  try {
    let res;
    try {
      recordRestRequest();
      res = await fetch(INFO_URL, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
        signal: controller.signal
      });
    } catch (err) {
      if (err instanceof DOMException && err.name === "AbortError") {
        if (opts?.signal?.aborted) {
          throw new HyperliquidError("network", "Request cancelled.", false);
        }
        throw new HyperliquidError(
          "timeout",
          "Unable to retrieve Hyperliquid market data (timeout). Retrying\u2026",
          true
        );
      }
      throw new HyperliquidError(
        "network",
        "Unable to retrieve Hyperliquid market data (network). Retrying\u2026",
        true
      );
    }
    if (!res.ok) {
      const text = await res.text().catch(() => "");
      if (isRateLimitStatus(res.status)) {
        recordRateLimit();
        throw new HyperliquidError("rate-limited", errorMessageForStatus(res.status, text), true);
      }
      throw new HyperliquidError("api", errorMessageForStatus(res.status, text), res.status >= 500);
    }
    try {
      return await res.json();
    } catch {
      throw new HyperliquidError(
        "invalid-response",
        "Unable to retrieve Hyperliquid market data (invalid JSON). Retrying\u2026",
        true
      );
    }
  } finally {
    clearTimeout(timer);
    opts?.signal?.removeEventListener("abort", onAbort);
  }
}
var RETRY_POLICY = {
  maxRetries: 4,
  baseDelayMs: 500,
  maxDelayMs: 8e3,
  /** ±25% jitter so concurrent callers don't retry in lockstep. */
  jitterRatio: 0.25
};
function isRetryableError(err) {
  if (err instanceof HyperliquidError) {
    if (err.kind === "invalid-response") return false;
    return err.retryable;
  }
  return false;
}
function backoffDelayMs(attempt, random = Math.random) {
  const exp = RETRY_POLICY.baseDelayMs * 2 ** attempt;
  const capped = Math.min(exp, RETRY_POLICY.maxDelayMs);
  const jitter = 1 + (random() * 2 - 1) * RETRY_POLICY.jitterRatio;
  return Math.max(0, Math.round(capped * jitter));
}
var sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
async function postInfoWithRetry(body, opts) {
  const maxRetries = opts?.maxRetries ?? RETRY_POLICY.maxRetries;
  let attempt = 0;
  for (; ; ) {
    try {
      return await postInfo(body, opts);
    } catch (err) {
      const retryable = isRetryableError(err);
      if (!retryable || attempt >= maxRetries || opts?.signal?.aborted) throw err;
      await sleep(backoffDelayMs(attempt, opts?.random));
      attempt += 1;
    }
  }
}

// src/market/hyperliquid/markets.ts
function toNumberOrNull(value) {
  if (value === null || value === void 0 || value === "") return null;
  const n = Number(value);
  return Number.isFinite(n) ? n : null;
}
function dayChangePct(markPx, prevDayPx) {
  if (markPx === null || prevDayPx === null || prevDayPx === 0) return null;
  return (markPx - prevDayPx) / prevDayPx * 100;
}
function normalizeMarket(entry, ctx) {
  const markPrice = toNumberOrNull(ctx?.markPx);
  const oraclePrice = toNumberOrNull(ctx?.oraclePx);
  const midPrice = toNumberOrNull(ctx?.midPx);
  const prevDayPrice = toNumberOrNull(ctx?.prevDayPx);
  const dayVolumeNotional = toNumberOrNull(ctx?.dayNtlVlm);
  const fundingRate = toNumberOrNull(ctx?.funding);
  const openInterestCoins = toNumberOrNull(ctx?.openInterest);
  return {
    symbol: entry.name,
    markPrice,
    oraclePrice,
    dayVolumeNotional,
    dayChangePct: dayChangePct(markPrice ?? midPrice, prevDayPrice),
    fundingRate,
    openInterestCoins,
    openInterestNotional: openInterestCoins !== null && markPrice !== null ? openInterestCoins * markPrice : null,
    prevDayPrice,
    midPrice
  };
}
function normalizeMetaAndAssetCtxs(payload) {
  if (!Array.isArray(payload) || payload.length !== 2) {
    throw new HyperliquidError(
      "invalid-response",
      "Unable to retrieve Hyperliquid market data (bad universe shape). Retrying\u2026"
    );
  }
  const [meta, ctxs] = payload;
  const out = normalizeDexTuple(meta, ctxs);
  if (out.length === 0) {
    throw new HyperliquidError(
      "invalid-response",
      "Unable to retrieve Hyperliquid market data (empty universe). Retrying\u2026"
    );
  }
  return out;
}
function normalizeDexTuple(meta, ctxs) {
  if (!meta || !Array.isArray(meta.universe) || !Array.isArray(ctxs)) {
    throw new HyperliquidError(
      "invalid-response",
      "Unable to retrieve Hyperliquid market data (bad universe shape). Retrying\u2026"
    );
  }
  const out = [];
  meta.universe.forEach((entry, i) => {
    if (!entry || typeof entry.name !== "string" || entry.isDelisted) return;
    out.push(normalizeMarket(entry, ctxs[i]));
  });
  return out;
}
function normalizePerpDexs(payload) {
  if (!Array.isArray(payload)) {
    throw new HyperliquidError(
      "invalid-response",
      "Unable to retrieve Hyperliquid market data (bad dex list shape). Retrying\u2026"
    );
  }
  const out = [];
  for (const entry of payload) {
    if (entry === null) {
      if (!out.includes("")) out.push("");
      continue;
    }
    if (typeof entry === "object" && entry !== null) {
      const name = entry.name;
      if (typeof name === "string" && name.length > 0 && !out.includes(name)) {
        out.push(name);
      }
    }
  }
  if (out.length === 0) {
    throw new HyperliquidError(
      "invalid-response",
      "Unable to retrieve Hyperliquid market data (empty dex list). Retrying\u2026"
    );
  }
  out.sort((a, b) => a === "" ? -1 : b === "" ? 1 : 0);
  return out;
}
function mergeDexMarkets(lists) {
  const seen = /* @__PURE__ */ new Set();
  const out = [];
  for (const list of lists) {
    for (const m of list) {
      if (seen.has(m.symbol)) continue;
      seen.add(m.symbol);
      out.push(m);
    }
  }
  if (out.length === 0) {
    throw new HyperliquidError(
      "invalid-response",
      "Unable to retrieve Hyperliquid market data (empty universe). Retrying\u2026"
    );
  }
  return out;
}

// src/market/cache.ts
var store = /* @__PURE__ */ new Map();
var MAX_ENTRIES = 200;
function evictIfNeeded() {
  if (store.size <= MAX_ENTRIES) return;
  const oldest = store.keys().next();
  if (!oldest.done) store.delete(oldest.value);
}
async function cached(key, ttlMs, fetcher) {
  const now = Date.now();
  if (ttlMs <= 0) {
    const value = await fetcher();
    return value;
  }
  const hit = store.get(key);
  if (hit && "value" in hit && hit.expiresAt > now) {
    recordCacheHit();
    return hit.value;
  }
  if (hit && "promise" in hit && hit.expiresAt > now) {
    recordCacheHit();
    return hit.promise;
  }
  recordCacheMiss();
  const promise = fetcher().then((value) => {
    store.set(key, { value, expiresAt: Date.now() + ttlMs });
    evictIfNeeded();
    return value;
  }).catch((err) => {
    if (store.get(key) !== void 0) {
      const current = store.get(key);
      if (current && "promise" in current) store.delete(key);
    }
    throw err;
  });
  store.set(key, { promise, expiresAt: now + ttlMs });
  evictIfNeeded();
  return promise;
}
var CACHE_TTL = {
  // Snapshot polls run every 30s; 45s TTL keeps them inside the 60s LIVE
  // window while cutting per-dex refetches by roughly a third.
  marketsMs: 45e3,
  // Candles refresh on 30–60s cadences; 30s TTL with grid-aligned keys
  // lets overlapping consumers share entries instead of refetching.
  candlesMs: 3e4
};

// src/market/hyperliquid/timeframes.ts
var TIMEFRAME_MS = {
  "1m": 6e4,
  "5m": 5 * 6e4,
  "15m": 15 * 6e4,
  "1h": 60 * 6e4,
  "4h": 4 * 60 * 6e4
};
function toHyperliquidInterval(tf) {
  return tf;
}
function timeframeToMs(tf) {
  return TIMEFRAME_MS[tf];
}
function getCandleWindow(tf, endTime = Date.now(), limit = 300) {
  const span = TIMEFRAME_MS[tf] * limit;
  return { startTime: endTime - span, endTime };
}

// src/market/hyperliquid/candles.ts
function toFiniteNumber(value, field) {
  const n = typeof value === "number" ? value : Number(value);
  if (!Number.isFinite(n)) {
    throw new HyperliquidError(
      "invalid-response",
      `Unable to retrieve Hyperliquid market data (bad candle field ${field}). Retrying\u2026`
    );
  }
  return n;
}
function normalizeCandle(raw) {
  if (!raw || typeof raw.t !== "number") {
    throw new HyperliquidError(
      "invalid-response",
      "Unable to retrieve Hyperliquid market data (bad candle shape). Retrying\u2026"
    );
  }
  return {
    timestamp: raw.t,
    open: toFiniteNumber(raw.o, "o"),
    high: toFiniteNumber(raw.h, "h"),
    low: toFiniteNumber(raw.l, "l"),
    close: toFiniteNumber(raw.c, "c"),
    volume: toFiniteNumber(raw.v, "v")
  };
}
function normalizeCandles(payload) {
  if (!Array.isArray(payload)) {
    throw new HyperliquidError(
      "invalid-response",
      "Unable to retrieve Hyperliquid market data (bad candles shape). Retrying\u2026"
    );
  }
  const seen = /* @__PURE__ */ new Set();
  const out = [];
  for (const raw of payload) {
    try {
      const c = normalizeCandle(raw);
      if (seen.has(c.timestamp)) continue;
      seen.add(c.timestamp);
      out.push(c);
    } catch {
      continue;
    }
  }
  out.sort((a, b) => a.timestamp - b.timestamp);
  return out;
}
function coinForRequest(symbol) {
  return symbol.includes(":") ? symbol : symbol.toUpperCase();
}
async function getCandles(symbol, timeframe, startTime, endTime, opts) {
  const coin = coinForRequest(symbol);
  const payload = await postInfoWithRetry(
    {
      type: "candleSnapshot",
      req: {
        coin,
        interval: toHyperliquidInterval(timeframe),
        startTime,
        endTime
      }
    },
    opts
  );
  const candles = normalizeCandles(payload);
  if (candles.length === 0) {
    throw new HyperliquidError(
      "missing-candles",
      `No candle data for ${coin} on ${timeframe}. Try another timeframe.`,
      false
    );
  }
  return candles;
}

// src/market/hyperliquid/index.ts
var DEX_LIST_TTL_MS = 10 * 60 * 1e3;
var DEX_FANOUT_LIMIT = 4;
async function getMarkets(opts) {
  const run = async () => {
    let dexes;
    try {
      dexes = await cached("hl:perpDexs", DEX_LIST_TTL_MS, async () => {
        const payload = await postInfoWithRetry({ type: "perpDexs" }, opts);
        return normalizePerpDexs(payload);
      });
    } catch (err) {
      if (err instanceof HyperliquidError && !err.retryable) throw err;
      dexes = [""];
    }
    const slots = new Array(dexes.length).fill(null);
    let firstError = null;
    let next = 0;
    const fetchOne = async (dex) => {
      const payload = await postInfoWithRetry(
        dex === "" ? { type: "metaAndAssetCtxs" } : { type: "metaAndAssetCtxs", dex },
        opts
      );
      return normalizeMetaAndAssetCtxs(payload);
    };
    const workers = Array.from(
      { length: Math.min(DEX_FANOUT_LIMIT, dexes.length) },
      async () => {
        while (next < dexes.length) {
          const i = next++;
          try {
            slots[i] = await fetchOne(dexes[i]);
          } catch (err) {
            if (firstError === null) firstError = err;
          }
        }
      }
    );
    await Promise.all(workers);
    const lists = slots.filter((l) => l !== null);
    if (lists.length === 0) {
      if (firstError instanceof HyperliquidError) throw firstError;
      throw new HyperliquidError(
        "api",
        "Unable to retrieve Hyperliquid market data. Retrying\u2026",
        true
      );
    }
    return {
      markets: mergeDexMarkets(lists),
      updatedAt: Date.now()
    };
  };
  if (opts?.bypassCache) return run();
  return cached("hl:markets", CACHE_TTL.marketsMs, run);
}
function candleCacheKey(symbol, timeframe, startTime, endTime) {
  const grid = timeframeToMs(timeframe);
  const s = Math.floor(startTime / grid) * grid;
  const e = Math.ceil(endTime / grid) * grid;
  return `hl:candles:${symbol.toUpperCase()}:${timeframe}:${s}:${e}`;
}
async function getCachedCandles(symbol, timeframe, startTime, endTime) {
  const key = candleCacheKey(symbol, timeframe, startTime, endTime);
  return cached(key, CACHE_TTL.candlesMs, async () => ({
    candles: await getCandles(symbol, timeframe, startTime, endTime),
    updatedAt: Date.now()
  }));
}

// src/indicators/ema.ts
function emaSeries(values, period) {
  const out = new Array(values.length).fill(null);
  if (!Number.isInteger(period) || period < 2) return out;
  if (values.length < period) return out;
  if (values.some((v) => !Number.isFinite(v))) return out;
  const k = 2 / (period + 1);
  let prev = 0;
  for (let i = 0; i < period; i++) prev += values[i];
  prev /= period;
  out[period - 1] = prev;
  for (let i = period; i < values.length; i++) {
    prev = values[i] * k + prev * (1 - k);
    out[i] = prev;
  }
  return out;
}
function lastEma(values, period) {
  if (values.length === 0) return null;
  const s = emaSeries(values, period);
  return s[s.length - 1];
}

// src/indicators/rsi.ts
function rsiSeries(closes, period = 14) {
  const out = new Array(closes.length).fill(null);
  if (!Number.isInteger(period) || period < 2) return out;
  if (closes.length < period + 1) return out;
  if (closes.some((v) => !Number.isFinite(v))) return out;
  let avgGain = 0;
  let avgLoss = 0;
  for (let i = 1; i <= period; i++) {
    const chg = closes[i] - closes[i - 1];
    if (chg > 0) avgGain += chg;
    else avgLoss -= chg;
  }
  avgGain /= period;
  avgLoss /= period;
  out[period] = rsiFromAverages(avgGain, avgLoss);
  for (let i = period + 1; i < closes.length; i++) {
    const chg = closes[i] - closes[i - 1];
    const gain = chg > 0 ? chg : 0;
    const loss = chg < 0 ? -chg : 0;
    avgGain = (avgGain * (period - 1) + gain) / period;
    avgLoss = (avgLoss * (period - 1) + loss) / period;
    out[i] = rsiFromAverages(avgGain, avgLoss);
  }
  return out;
}
function rsiFromAverages(avgGain, avgLoss) {
  if (avgLoss === 0) return avgGain === 0 ? 50 : 100;
  const rs = avgGain / avgLoss;
  return 100 - 100 / (1 + rs);
}

// src/indicators/macd.ts
function macdSeries(closes, fastPeriod = 12, slowPeriod = 26, signalPeriod = 9) {
  const out = closes.map(() => ({ line: null, signal: null, histogram: null }));
  if (closes.length === 0) return out;
  const fast = emaSeries(closes, fastPeriod);
  const slow = emaSeries(closes, slowPeriod);
  const lineIdx = [];
  for (let i = 0; i < closes.length; i++) {
    if (fast[i] !== null && slow[i] !== null) {
      const line = fast[i] - slow[i];
      out[i].line = line;
      lineIdx.push(i);
    }
  }
  if (lineIdx.length < signalPeriod) return out;
  const k = 2 / (signalPeriod + 1);
  let prev = 0;
  for (let j = 0; j < signalPeriod; j++) prev += out[lineIdx[j]].line;
  prev /= signalPeriod;
  const seedAt = lineIdx[signalPeriod - 1];
  out[seedAt].signal = prev;
  out[seedAt].histogram = out[seedAt].line - prev;
  for (let j = signalPeriod; j < lineIdx.length; j++) {
    const i = lineIdx[j];
    prev = out[i].line * k + prev * (1 - k);
    out[i].signal = prev;
    out[i].histogram = out[i].line - prev;
  }
  return out;
}

// src/indicators/atr.ts
function trueRanges(candles) {
  const out = [];
  for (let i = 0; i < candles.length; i++) {
    const c = candles[i];
    if (i === 0) {
      out.push(c.high - c.low);
    } else {
      const prev = candles[i - 1].close;
      out.push(
        Math.max(c.high - c.low, Math.abs(c.high - prev), Math.abs(c.low - prev))
      );
    }
  }
  return out;
}
function atrSeries(candles, period = 14) {
  const out = new Array(candles.length).fill(null);
  if (!Number.isInteger(period) || period < 2) return out;
  if (candles.length < period) return out;
  const tr = trueRanges(candles);
  if (tr.some((v) => !Number.isFinite(v))) return out;
  let prev = 0;
  for (let i = 0; i < period; i++) prev += tr[i];
  prev /= period;
  out[period - 1] = prev;
  for (let i = period; i < tr.length; i++) {
    prev = (prev * (period - 1) + tr[i]) / period;
    out[i] = prev;
  }
  return out;
}
function lastAtr(candles, period = 14) {
  if (candles.length === 0) return null;
  const s = atrSeries(candles, period);
  return s[s.length - 1];
}

// src/indicators/volume.ts
var VOLUME_LOOKBACK = 20;
var SPIKE_THRESHOLD = 2;
var HIGH_THRESHOLD = 1.5;
var NORMAL_THRESHOLD = 0.7;
function volumeStats(volumes, lookback = VOLUME_LOOKBACK) {
  if (!Number.isInteger(lookback) || lookback < 2) return null;
  if (volumes.length < lookback + 1) return null;
  const prior = volumes.slice(volumes.length - lookback - 1, volumes.length - 1);
  if (prior.some((v) => !Number.isFinite(v) || v < 0)) return null;
  const current = volumes[volumes.length - 1];
  if (!Number.isFinite(current) || current < 0) return null;
  const average = prior.reduce((a, b) => a + b, 0) / prior.length;
  if (average <= 0) return null;
  const relative = current / average;
  return { current, average, relative, spike: relative >= SPIKE_THRESHOLD };
}

// src/analysis/trend.ts
function classifyTrend(price, ema20, ema50, ema200, epsilon = 0) {
  if (price === null || ema20 === null || ema50 === null || ema200 === null || ![price, ema20, ema50, ema200].every(Number.isFinite)) {
    return null;
  }
  const gt = (a, b) => a > b + epsilon;
  const lt = (a, b) => a < b - epsilon;
  const bull = (gt(price, ema20) ? 1 : 0) + (gt(price, ema50) ? 1 : 0) + (gt(price, ema200) ? 1 : 0) + (gt(ema20, ema50) ? 1 : 0) + (gt(ema50, ema200) ? 1 : 0);
  const bear = (lt(price, ema20) ? 1 : 0) + (lt(price, ema50) ? 1 : 0) + (lt(price, ema200) ? 1 : 0) + (lt(ema20, ema50) ? 1 : 0) + (lt(ema50, ema200) ? 1 : 0);
  let label;
  if (bull === 5) label = "STRONG BULLISH";
  else if (bull === 4) label = "BULLISH";
  else if (bear === 5) label = "STRONG BEARISH";
  else if (bear === 4) label = "BEARISH";
  else label = "NEUTRAL";
  return { label, bullPoints: bull, bearPoints: bear };
}

// src/analysis/momentum.ts
function classifyMomentum(input) {
  const { rsiNow, rsiThen, histNow } = input;
  if (rsiNow === null || rsiThen === null || histNow === null || ![rsiNow, rsiThen, histNow].every(Number.isFinite)) {
    return null;
  }
  const recovering = input.crossedUp30 || rsiThen < 40 && rsiNow > rsiThen + 3;
  const fading = input.crossedDown70 || rsiThen > 60 && rsiNow < rsiThen - 3;
  const rising = rsiNow >= rsiThen + 1;
  const falling = rsiNow <= rsiThen - 1;
  let long = 0;
  if (rsiNow > 55) long += 0.25;
  else if (rsiNow > 50) long += 0.12;
  if (recovering) long += 0.25;
  else if (rising) long += 0.12;
  if (histNow > 0) long += 0.2;
  if (input.histRising) long += 0.15;
  if (input.aboveSignal === true) long += 0.15;
  let short = 0;
  if (rsiNow < 45) short += 0.25;
  else if (rsiNow < 50) short += 0.12;
  if (fading) short += 0.25;
  else if (falling) short += 0.12;
  if (histNow < 0) short += 0.2;
  if (input.histFalling) short += 0.15;
  if (input.aboveSignal === false) short += 0.15;
  long = Math.min(1, long);
  short = Math.min(1, short);
  let label;
  if (long >= 0.7 && long - short >= 0.3) label = "STRONG POSITIVE";
  else if (short >= 0.7 && short - long >= 0.3) label = "STRONG NEGATIVE";
  else if (long - short >= 0.2) label = "POSITIVE";
  else if (short - long >= 0.2) label = "NEGATIVE";
  else label = "NEUTRAL";
  return { label, longScore: long, shortScore: short, recovering, fading };
}
function crossedUp(series, level, window = 4) {
  const vals = series.filter((v) => v !== null).slice(-(window + 1));
  if (vals.length < 2) return false;
  for (let i = 1; i < vals.length; i++) {
    if (vals[i - 1] <= level && vals[i] > level) return true;
  }
  return false;
}
function crossedDown(series, level, window = 4) {
  const vals = series.filter((v) => v !== null).slice(-(window + 1));
  if (vals.length < 2) return false;
  for (let i = 1; i < vals.length; i++) {
    if (vals[i - 1] >= level && vals[i] < level) return true;
  }
  return false;
}
function isRising(series, window = 3) {
  const vals = series.filter((v) => v !== null).slice(-window);
  if (vals.length < window) return false;
  for (let i = 1; i < vals.length; i++) {
    if (vals[i] <= vals[i - 1]) return false;
  }
  return true;
}
function isFalling(series, window = 3) {
  const vals = series.filter((v) => v !== null).slice(-window);
  if (vals.length < window) return false;
  for (let i = 1; i < vals.length; i++) {
    if (vals[i] >= vals[i - 1]) return false;
  }
  return true;
}

// src/analysis/volumeProfile.ts
function classifyVolume(relativeVolume, spike) {
  if (relativeVolume === null || !Number.isFinite(relativeVolume)) return null;
  if (relativeVolume >= HIGH_THRESHOLD) {
    return { label: "HIGH", score: spike ? 1 : 0.75, spike };
  }
  if (relativeVolume >= NORMAL_THRESHOLD) {
    return { label: "NORMAL", score: 0.5, spike };
  }
  return { label: "LOW", score: 0.15, spike };
}

// src/analysis/swings.ts
function detectSwings(candles, strength = 3, lookback = 120) {
  if (!Number.isInteger(strength) || strength < 1) return [];
  if (candles.length < strength * 2 + 1) return [];
  const start = Math.max(0, candles.length - lookback);
  const out = [];
  const end = candles.length - strength;
  for (let i = Math.max(start + strength, strength); i < end; i++) {
    const h = candles[i].high;
    const l = candles[i].low;
    let isHigh = true;
    let isLow = true;
    for (let j = i - strength; j <= i + strength; j++) {
      if (j === i) continue;
      if (candles[j].high >= h) isHigh = false;
      if (candles[j].low <= l) isLow = false;
      if (!isHigh && !isLow) break;
    }
    if (isHigh) {
      out.push({ index: i, timestamp: candles[i].timestamp, price: h, type: "high" });
    } else if (isLow) {
      out.push({ index: i, timestamp: candles[i].timestamp, price: l, type: "low" });
    }
  }
  return out;
}

// src/analysis/levels.ts
function buildLevels(swings, price, atr, toleranceAtrMult = 0.5) {
  const empty = {
    nearestSupport: null,
    strongSupport: null,
    nearestResistance: null,
    strongResistance: null
  };
  if (!Number.isFinite(price) || !Number.isFinite(atr) || atr <= 0) return empty;
  if (swings.length === 0) return empty;
  const tolerance = Math.max(atr * toleranceAtrMult, price * 1e-3);
  const cluster = (type) => {
    const pts = swings.filter((s) => s.type === type).sort((a, b) => a.price - b.price);
    const zones = [];
    for (const p of pts) {
      const z = zones.find((z2) => Math.abs(z2.price - p.price) <= tolerance);
      if (z) {
        z.price = (z.price * z.touches + p.price) / (z.touches + 1);
        z.touches += 1;
        z.lastIndex = Math.max(z.lastIndex, p.index);
      } else {
        zones.push({ price: p.price, touches: 1, lastIndex: p.index });
      }
    }
    return zones;
  };
  const maxIndex = Math.max(...swings.map((s) => s.index));
  const score = (z) => {
    const distAtr = Math.abs(z.price - price) / atr;
    const touchScore = Math.min(1, z.touches / 3);
    const recency = Math.max(0, 1 - (maxIndex - z.lastIndex) / 120);
    const distScore = Math.max(0, 1 - distAtr / 10);
    return {
      price: z.price,
      touches: z.touches,
      strength: touchScore * 0.5 + recency * 0.25 + distScore * 0.25
    };
  };
  const supports = cluster("low").map((z) => ({ zone: z, level: score(z) })).filter(({ zone }) => zone.price < price).sort((a, b) => b.zone.price - a.zone.price);
  const resistances = cluster("high").map((z) => ({ zone: z, level: score(z) })).filter(({ zone }) => zone.price > price).sort((a, b) => a.zone.price - b.zone.price);
  const strongest = (list) => {
    if (list.length === 0) return null;
    return list.reduce((a, b) => b.level.strength > a.level.strength ? b : a).level;
  };
  return {
    nearestSupport: supports[0]?.level ?? null,
    strongSupport: strongest(supports),
    nearestResistance: resistances[0]?.level ?? null,
    strongResistance: strongest(resistances)
  };
}

// src/analysis/structure.ts
var CHOP_ER_THRESHOLD = 0.25;
var ER_LOOKBACK = 50;
function efficiencyRatio(closes, lookback = ER_LOOKBACK) {
  if (closes.length < lookback + 1) return null;
  const window = closes.slice(closes.length - lookback - 1);
  let path = 0;
  for (let i = 1; i < window.length; i++) path += Math.abs(window[i] - window[i - 1]);
  if (path <= 0) return 0;
  return Math.abs(window[window.length - 1] - window[0]) / path;
}
function classifyStructure(candles, swings, atr) {
  const base = {
    label: "RANGE",
    longScore: 0,
    shortScore: 0,
    brokeAbove: false,
    brokeBelow: false,
    retestHeldAbove: false,
    retestHeldBelow: false,
    falseBreakoutDown: false,
    falseBreakoutUp: false,
    lastSwingHigh: null,
    lastSwingLow: null
  };
  if (candles.length < 10 || atr === null || !Number.isFinite(atr) || atr <= 0) {
    return null;
  }
  const highs = swings.filter((s) => s.type === "high");
  const lows = swings.filter((s) => s.type === "low");
  const lastHigh = highs.length > 0 ? highs[highs.length - 1].price : null;
  const lastLow = lows.length > 0 ? lows[lows.length - 1].price : null;
  base.lastSwingHigh = lastHigh;
  base.lastSwingLow = lastLow;
  let long = 0;
  let short = 0;
  if (highs.length >= 2 && lows.length >= 2) {
    const hh = highs[highs.length - 1].price > highs[highs.length - 2].price;
    const hl = lows[lows.length - 1].price > lows[lows.length - 2].price;
    const lh = highs[highs.length - 1].price < highs[highs.length - 2].price;
    const ll = lows[lows.length - 1].price < lows[lows.length - 2].price;
    if (hh && hl) {
      base.label = "BULLISH";
      long += 0.5;
    } else if (lh && ll) {
      base.label = "BEARISH";
      short += 0.5;
    }
  }
  const close = candles[candles.length - 1].close;
  const buf = atr * 0.1;
  if (lastHigh !== null && close > lastHigh + buf) {
    base.brokeAbove = true;
    long += 0.25;
  }
  if (lastLow !== null && close < lastLow - buf) {
    base.brokeBelow = true;
    short += 0.25;
  }
  const recent = candles.slice(-6);
  if (base.brokeAbove && lastHigh !== null) {
    const held = recent.every((c) => c.low >= lastHigh - atr * 0.25);
    if (held) {
      base.retestHeldAbove = true;
      long += 0.25;
    }
  }
  if (base.brokeBelow && lastLow !== null) {
    const held = recent.every((c) => c.high <= lastLow + atr * 0.25);
    if (held) {
      base.retestHeldBelow = true;
      short += 0.25;
    }
  }
  if (lastHigh !== null) {
    const brokeIdx = findLastBreakoutClose(candles, lastHigh, "up");
    if (brokeIdx !== null && closedBackInside(candles, brokeIdx, lastHigh, "up")) {
      base.falseBreakoutUp = true;
      long = Math.min(long, 0.25);
    }
  }
  if (lastLow !== null) {
    const brokeIdx = findLastBreakoutClose(candles, lastLow, "down");
    if (brokeIdx !== null && closedBackInside(candles, brokeIdx, lastLow, "down")) {
      base.falseBreakoutDown = true;
      short = Math.min(short, 0.25);
    }
  }
  base.longScore = Math.min(1, long);
  base.shortScore = Math.min(1, short);
  return base;
}
function findLastBreakoutClose(candles, level, dir) {
  for (let i = candles.length - 1; i >= Math.max(0, candles.length - 12); i--) {
    const c = candles[i].close;
    if (dir === "up" && c > level) return i;
    if (dir === "down" && c < level) return i;
  }
  return null;
}
function closedBackInside(candles, brokeIdx, level, dir) {
  for (let i = brokeIdx + 1; i < Math.min(candles.length, brokeIdx + 6); i++) {
    const c = candles[i].close;
    if (dir === "up" && c < level) return true;
    if (dir === "down" && c > level) return true;
  }
  return false;
}

// src/analysis/mtf.ts
var MTF_ORDER = ["4h", "1h", "15m", "5m"];
var TF_WEIGHT = {
  "4h": 0.4,
  "1h": 0.3,
  "15m": 0.2,
  "1m": 0,
  "5m": 0.1
};
function agreementOf(input) {
  if (!input.trend) return null;
  return (input.bullPoints - input.bearPoints) / 5;
}
function analyzeMtf(inputs) {
  const warnings = [];
  const tfs = MTF_ORDER.map((tf) => {
    const input = inputs[tf];
    if (!input || !input.trend) {
      return { timeframe: tf, trend: null, agreement: null, flavor: "INSUFFICIENT" };
    }
    const agreement = agreementOf(input);
    return { timeframe: tf, trend: input.trend, agreement, flavor: "RANGE" };
  });
  for (const tf of ["4h", "1h"]) {
    const t = tfs.find((x) => x.timeframe === tf);
    if (t && t.agreement !== null) {
      t.flavor = t.agreement > 0.4 ? "BULLISH" : t.agreement < -0.4 ? "BEARISH" : "RANGE";
    }
  }
  const h1 = tfs.find((t) => t.timeframe === "1h");
  const m15 = tfs.find((t) => t.timeframe === "15m");
  const m5 = tfs.find((t) => t.timeframe === "5m");
  const h1Bull = (h1?.agreement ?? 0) > 0.2;
  const h1Bear = (h1?.agreement ?? 0) < -0.2;
  if (m15 && m15.agreement !== null) {
    const a = m15.agreement;
    const revUp = inputs["15m"]?.reversalUp ?? false;
    const revDown = inputs["15m"]?.reversalDown ?? false;
    m15.flavor = a > 0.4 ? "BULLISH" : a < -0.4 ? "BEARISH" : h1Bull && a <= 0.2 ? "PULLBACK" : h1Bear && a >= -0.2 ? "BEAR_RALLY" : revUp ? "BULLISH_REVERSAL" : revDown ? "BEARISH_REVERSAL" : "RANGE";
  }
  if (m5 && m5.agreement !== null) {
    const a = m5.agreement;
    const revUp = inputs["5m"]?.reversalUp ?? false;
    const revDown = inputs["5m"]?.reversalDown ?? false;
    m5.flavor = revUp && a >= -0.2 ? "BULLISH_REVERSAL" : revDown && a <= 0.2 ? "BEARISH_REVERSAL" : a > 0.4 ? "CONTINUATION" : a < -0.4 ? "BEARISH" : "RANGE";
  }
  let long = 0;
  let short = 0;
  let weightSum = 0;
  for (const t of tfs) {
    if (t.agreement === null) {
      warnings.push(`${t.timeframe} unavailable \u2014 excluded from MTF score.`);
      continue;
    }
    const w = TF_WEIGHT[t.timeframe];
    weightSum += w;
    long += Math.max(0, t.agreement) * w;
    short += Math.max(0, -t.agreement) * w;
  }
  if (weightSum > 0) {
    long /= weightSum;
    short /= weightSum;
  }
  const leadingLong = long >= short;
  const conflict = tfs.some(
    (t) => t.agreement === null ? false : leadingLong ? t.agreement < -0.6 : t.agreement > 0.6
  );
  if (conflict) {
    long *= 0.5;
    short *= 0.5;
    warnings.push("Timeframes conflict strongly \u2014 MTF score halved.");
  }
  return { tfs, longScore: long, shortScore: short, conflict, warnings };
}

// src/analysis/bounce.ts
var EMPTY_COMPONENTS = { support: 0, momentum: 0, volume: 0, structure: 0, mtf: 0 };
function scaleBuckets(b, targetTotal) {
  const sum = b.support + b.momentum + b.volume + b.structure + b.mtf;
  if (sum <= 0) return;
  const f = Math.min(1, targetTotal / sum);
  b.support = Math.round(b.support * f * 10) / 10;
  b.momentum = Math.round(b.momentum * f * 10) / 10;
  b.volume = Math.round(b.volume * f * 10) / 10;
  b.structure = Math.round(b.structure * f * 10) / 10;
  b.mtf = Math.round(b.mtf * f * 10) / 10;
}
var NEAR_LEVEL_ATR = 1;
function detectBounce(input) {
  const reasons = [];
  const warnings = [];
  let longPts = 0;
  let shortPts = 0;
  const longB = { ...EMPTY_COMPONENTS };
  const shortB = { ...EMPTY_COMPONENTS };
  const finish = (direction, score, b) => ({ direction, bounceScore: score, bounceReasons: reasons, bounceWarnings: warnings, components: { ...b } });
  const nearSupport = input.supportDistanceAtr !== null && input.supportDistanceAtr <= NEAR_LEVEL_ATR;
  const nearResistance = input.resistanceDistanceAtr !== null && input.resistanceDistanceAtr <= NEAR_LEVEL_ATR;
  if (nearSupport) {
    longPts += 25;
    longB.support += 25;
    reasons.push(`Holding near support (${input.supportDistanceAtr?.toFixed(2)} ATR away).`);
  } else {
    warnings.push("Price is not near a meaningful support \u2014 no LONG bounce.");
  }
  if (nearResistance) {
    shortPts += 25;
    shortB.support += 25;
    reasons.push(`Rejecting near resistance (${input.resistanceDistanceAtr?.toFixed(2)} ATR away).`);
  } else {
    warnings.push("Price is not near a meaningful resistance \u2014 no SHORT bounce.");
  }
  if (input.momentum.recovering) {
    longPts += 20;
    longB.momentum += 20;
    reasons.push("RSI recovering after weakness (not blindly oversold).");
  }
  if (input.momentum.fading) {
    shortPts += 20;
    shortB.momentum += 20;
    reasons.push("RSI fading after strength (not blindly overbought).");
  }
  if (input.momentum.longScore >= 0.5) {
    longPts += 15;
    longB.momentum += 15;
    reasons.push("MACD momentum improving on the setup timeframe.");
  }
  if (input.momentum.shortScore >= 0.5) {
    shortPts += 15;
    shortB.momentum += 15;
    reasons.push("MACD momentum deteriorating on the setup timeframe.");
  }
  if (input.volume.score >= 0.5) {
    longPts += nearSupport ? 15 : 5;
    longB.volume += nearSupport ? 15 : 5;
    shortPts += nearResistance ? 15 : 5;
    shortB.volume += nearResistance ? 15 : 5;
    if (input.volume.spike) reasons.push("Volume spike confirms interest at the level.");
    else reasons.push("Healthy volume backs the move.");
  } else {
    warnings.push("Low volume \u2014 any bounce lacks confirmation.");
  }
  const m5 = input.mtf.tfs.find((t) => t.timeframe === "5m");
  if (m5?.flavor === "BULLISH_REVERSAL" || m5?.flavor === "CONTINUATION") {
    longPts += 15;
    longB.mtf += 15;
    reasons.push(`Lower timeframe confirms (${m5.flavor}).`);
  }
  if (m5?.flavor === "BEARISH_REVERSAL" || m5?.flavor === "BEARISH") {
    shortPts += 15;
    shortB.mtf += 15;
    reasons.push(`Lower timeframe confirms (${m5.flavor}).`);
  }
  const h4 = input.mtf.tfs.find((t) => t.timeframe === "4h");
  const h4Agreement = h4?.agreement ?? 0;
  if (h4Agreement > -0.6) {
    longPts += 10;
    longB.mtf += 10;
  } else {
    warnings.push("Higher timeframe strongly bearish \u2014 LONG bounce vetoed.");
    longPts = Math.min(longPts, 30);
    scaleBuckets(longB, longPts);
  }
  if (h4Agreement < 0.6) {
    shortPts += 10;
    shortB.mtf += 10;
  } else {
    warnings.push("Higher timeframe strongly bullish \u2014 SHORT bounce vetoed.");
    shortPts = Math.min(shortPts, 30);
    scaleBuckets(shortB, shortPts);
  }
  if (input.structure.label === "BULLISH" && nearSupport) {
    longPts += 5;
    longB.structure += 5;
    reasons.push("Market structure is bullish (HH/HL).");
  }
  if (input.structure.label === "BEARISH" && nearResistance) {
    shortPts += 5;
    shortB.structure += 5;
    reasons.push("Market structure is bearish (LH/LL).");
  }
  longPts = Math.min(100, longPts);
  shortPts = Math.min(100, shortPts);
  if (longPts >= shortPts && longPts >= 60 && nearSupport) {
    return finish("LONG", longPts, longB);
  }
  if (shortPts > longPts && shortPts >= 60 && nearResistance) {
    return finish("SHORT", shortPts, shortB);
  }
  return finish(null, Math.max(longPts, shortPts), longPts >= shortPts ? longB : shortB);
}

// src/analysis/scoring.ts
var MIN_EDGE = 10;
var MIN_SCORE = 40;
function classifyStrength(score) {
  if (score >= 90) return "HIGH-CONFLUENCE SETUP";
  if (score >= 75) return "STRONG SETUP";
  if (score >= 60) return "SETUP";
  if (score >= 40) return "WATCH";
  return "WAIT";
}
function clamp(n, lo, hi) {
  return Math.min(hi, Math.max(lo, n));
}
function calculateSignalScore(input) {
  const longC = {
    trend: clamp(input.trendLong, 0, 1) * 25,
    momentum: clamp(input.momentumLong, 0, 1) * 20,
    volume: clamp(input.volume, 0, 1) * 15,
    structure: clamp(input.structureLong, 0, 1) * 20,
    mtf: clamp(input.mtfLong, 0, 1) * 20
  };
  const shortC = {
    trend: clamp(input.trendShort, 0, 1) * 25,
    momentum: clamp(input.momentumShort, 0, 1) * 20,
    volume: clamp(input.volume, 0, 1) * 15,
    structure: clamp(input.structureShort, 0, 1) * 20,
    mtf: clamp(input.mtfShort, 0, 1) * 20
  };
  const longScore = round1(longC.trend + longC.momentum + longC.volume + longC.structure + longC.mtf);
  const shortScore = round1(shortC.trend + shortC.momentum + shortC.structure + shortC.mtf + shortC.volume);
  const reasons = [];
  const warnings = [];
  let direction = "WAIT";
  let score = Math.max(longScore, shortScore);
  let components = { trend: 0, momentum: 0, volume: 0, structure: 0, mtf: 0 };
  if (score < MIN_SCORE) {
    warnings.push(`Confluence too low (${score}/100) \u2014 WAIT.`);
  } else if (Math.abs(longScore - shortScore) < MIN_EDGE) {
    warnings.push(
      `Mixed evidence LONG ${longScore} vs SHORT ${shortScore} \u2014 WAIT. Never force a trade.`
    );
  } else if (longScore > shortScore) {
    direction = "LONG";
    components = longC;
    reasons.push(`Bullish confluence ${longScore}/100 outweighs bearish ${shortScore}/100.`);
  } else {
    direction = "SHORT";
    components = shortC;
    reasons.push(`Bearish confluence ${shortScore}/100 outweighs bullish ${longScore}/100.`);
  }
  return {
    longScore,
    shortScore,
    score: round1(score),
    direction,
    classification: direction === "WAIT" ? "WAIT" : classifyStrength(score),
    components: roundComponents(components),
    reasons,
    warnings
  };
}
function round1(n) {
  return Math.round(n * 10) / 10;
}
function roundComponents(c) {
  return {
    trend: round1(c.trend),
    momentum: round1(c.momentum),
    volume: round1(c.volume),
    structure: round1(c.structure),
    mtf: round1(c.mtf)
  };
}

// src/analysis/tradeplan.ts
var ENTRY_ATR_CAP = 1;
var INV_BUFFER_ATR = 0.25;
var MIN_R = [1, 2, 3];
function buildTradePlan(input) {
  const { direction, price, atr, levels, structure } = input;
  if (![price, atr].every(Number.isFinite) || atr <= 0 || price <= 0) return null;
  return direction === "LONG" ? buildLong(price, atr, levels, structure) : buildShort(price, atr, levels, structure);
}
function buildLong(price, atr, levels, structure) {
  const support = levels.nearestSupport?.price ?? structure.lastSwingLow;
  if (support === null || support === void 0) return null;
  const entryLow = support - atr * 0.1;
  const entryHigh = Math.min(price, support + atr * ENTRY_ATR_CAP);
  if (!(entryHigh > entryLow)) return null;
  const entryMid = (entryLow + entryHigh) / 2;
  const swingLow = structure.lastSwingLow;
  const invalidation = Math.min(support, swingLow ?? support) - atr * INV_BUFFER_ATR;
  if (!(invalidation < entryLow)) return null;
  const risk = entryMid - invalidation;
  if (!(risk > 0)) return null;
  const res1 = levels.nearestResistance?.price ?? null;
  const res2 = levels.strongResistance?.price ?? structure.lastSwingHigh ?? null;
  const tp1 = Math.max(res1 ?? -Infinity, entryMid + MIN_R[0] * risk);
  const tp2raw = Math.max(res2 ?? -Infinity, entryMid + MIN_R[1] * risk);
  const tp2 = Math.max(tp2raw, tp1 + 0.25 * risk);
  const tp3 = Math.max(tp2 + 0.5 * risk, entryMid + MIN_R[2] * risk);
  return {
    entryLow: r4(entryLow),
    entryHigh: r4(entryHigh),
    invalidation: r4(invalidation),
    tp1: r4(tp1),
    tp2: r4(tp2),
    tp3: r4(tp3),
    riskReward: Math.round(((tp1 + tp2 + tp3) / 3 - entryMid) / risk * 100) / 100
  };
}
function buildShort(price, atr, levels, structure) {
  const resistance = levels.nearestResistance?.price ?? structure.lastSwingHigh;
  if (resistance === null || resistance === void 0) return null;
  const entryLow = Math.max(price, resistance - atr * ENTRY_ATR_CAP);
  const entryHigh = resistance + atr * 0.1;
  if (!(entryHigh > entryLow)) return null;
  const entryMid = (entryLow + entryHigh) / 2;
  const swingHigh = structure.lastSwingHigh;
  const invalidation = Math.max(resistance, swingHigh ?? resistance) + atr * INV_BUFFER_ATR;
  if (!(invalidation > entryHigh)) return null;
  const risk = invalidation - entryMid;
  if (!(risk > 0)) return null;
  const sup1 = levels.nearestSupport?.price ?? null;
  const sup2 = levels.strongSupport?.price ?? structure.lastSwingLow ?? null;
  const tp1 = Math.min(sup1 ?? Infinity, entryMid - MIN_R[0] * risk);
  const tp2raw = Math.min(sup2 ?? Infinity, entryMid - MIN_R[1] * risk);
  const tp2 = Math.min(tp2raw, tp1 - 0.25 * risk);
  const tp3 = Math.min(tp2 - 0.5 * risk, entryMid - MIN_R[2] * risk);
  return {
    entryLow: r4(entryLow),
    entryHigh: r4(entryHigh),
    invalidation: r4(invalidation),
    tp1: r4(tp1),
    tp2: r4(tp2),
    tp3: r4(tp3),
    riskReward: Math.round((entryMid - (tp1 + tp2 + tp3) / 3) / risk * 100) / 100
  };
}
function r4(n) {
  return Math.round(n * 1e4) / 1e4;
}

// src/signals/quality.ts
var MIN_RISK_REWARD = 1.5;
var MAX_RISK_ATR = 4;
var WILD_ATR_PCT = 5;
var MAX_EXTENSION_ATR = 6;
function assessQuality(signal) {
  const mtf = signal.multiTimeframe;
  const agreement = mtf === null ? 0 : signal.direction === "LONG" ? mtf.longScore : signal.direction === "SHORT" ? mtf.shortScore : 0;
  return classifyQuality({
    strength: signal.signalStrength,
    mtfAgreement: agreement,
    mtfConflict: mtf?.conflict ?? false,
    riskReward: signal.riskReward,
    riskAtr: signal.riskAtr,
    atrPct: signal.atrPct,
    falseBreakout: signal.falseBreakout
  });
}
function classifyQuality(input) {
  const { strength, mtfAgreement, mtfConflict, riskReward, riskAtr, atrPct, falseBreakout } = input;
  if (riskReward === null || riskReward < MIN_RISK_REWARD) return "LOW QUALITY";
  if (riskAtr !== null && riskAtr > MAX_RISK_ATR) return "LOW QUALITY";
  if (atrPct !== null && atrPct > WILD_ATR_PCT) return "LOW QUALITY";
  if (falseBreakout) return "LOW QUALITY";
  let points = 0;
  if (strength >= 90) points += 3;
  else if (strength >= 75) points += 2;
  else if (strength >= 60) points += 1;
  if (mtfAgreement >= 0.6 && !mtfConflict) points += 2;
  else if (mtfAgreement >= 0.4) points += 1;
  if (riskReward >= 2.5) points += 2;
  else if (riskReward >= 2) points += 1;
  if (riskAtr !== null && riskAtr <= 2) points += 1;
  if (atrPct !== null && atrPct <= 2) points += 1;
  if (points >= 7) return "HIGH QUALITY";
  if (points >= 4) return "MEDIUM QUALITY";
  return "LOW QUALITY";
}

// src/analysis/signal.ts
var SETUP_MIN_CANDLES = 210;
var TREND_MIN_CANDLES = 200;
function buildSignal(input) {
  const { symbol, setupTimeframe } = input;
  const setup = input.candlesByTf[setupTimeframe] ?? [];
  const now = Date.now();
  const dataTimestamp = setup.length > 0 ? setup[setup.length - 1].timestamp : 0;
  const insufficient = (warnings2) => ({
    status: "INSUFFICIENT_DATA",
    signal: {
      symbol,
      timestamp: now,
      timeframe: setupTimeframe,
      direction: "WAIT",
      signalStrength: 0,
      classification: "WAIT",
      entryLow: null,
      entryHigh: null,
      invalidation: null,
      tp1: null,
      tp2: null,
      tp3: null,
      riskReward: null,
      trend: "INSUFFICIENT",
      momentum: "INSUFFICIENT",
      rsi: null,
      volume: "INSUFFICIENT",
      marketStructure: "INSUFFICIENT",
      brokeAbove: false,
      brokeBelow: false,
      retestHeld: false,
      riskAtr: null,
      atrPct: null,
      falseBreakout: false,
      multiTimeframe: null,
      components: { trend: 0, momentum: 0, volume: 0, structure: 0, mtf: 0 },
      bounce: null,
      reasons: [],
      warnings: warnings2,
      dataTimestamp,
      longScore: 0,
      shortScore: 0
    }
  });
  if (setup.length < SETUP_MIN_CANDLES) {
    return insufficient([
      `INSUFFICIENT DATA: ${setup.length}/${SETUP_MIN_CANDLES} ${setupTimeframe} candles \u2014 EMA200 and full indicators need more history.`
    ]);
  }
  const closes = setup.map((c) => c.close);
  const volumes = setup.map((c) => c.volume);
  const price = closes[closes.length - 1];
  const e20 = lastEma(closes, 20);
  const e50 = lastEma(closes, 50);
  const e200 = lastEma(closes, 200);
  const rsi = rsiSeries(closes, 14);
  const rsiNow = rsi[rsi.length - 1];
  const rsiThen = rsi[rsi.length - 6] ?? null;
  const macd = macdSeries(closes);
  const hist = macd.map((m) => m.histogram);
  const histNow = hist[hist.length - 1];
  const macdLast = macd[macd.length - 1];
  const aboveSignal = macdLast.line !== null && macdLast.signal !== null ? macdLast.line > macdLast.signal : null;
  const atr = lastAtr(setup, 14);
  const vol = volumeStats(volumes, 20);
  const missing = [];
  if (e20 === null || e50 === null || e200 === null) missing.push("EMA20/50/200");
  if (rsiNow === null) missing.push("RSI14");
  if (histNow === null || aboveSignal === null) missing.push("MACD");
  if (atr === null) missing.push("ATR14");
  if (vol === null) missing.push("volume average");
  if (missing.length > 0) {
    return insufficient([`INSUFFICIENT DATA: unreliable ${missing.join(", ")}.`]);
  }
  if (e20 === null || e50 === null || e200 === null || rsiNow === null || histNow === null || aboveSignal === null || atr === null || vol === null) {
    return insufficient(["INSUFFICIENT DATA: classification inputs incomplete."]);
  }
  const trend = classifyTrend(price, e20, e50, e200, atr * 0.05);
  const momentum = classifyMomentum({
    rsiNow,
    rsiThen,
    crossedUp30: crossedUp(rsi, 30),
    crossedDown70: crossedDown(rsi, 70),
    histNow,
    histRising: isRising(hist, 3),
    histFalling: isFalling(hist, 3),
    aboveSignal
  });
  const volumeP = classifyVolume(vol.relative, vol.spike);
  const swings = detectSwings(setup, 3, 120);
  const levels = buildLevels(swings, price, atr);
  const structure = classifyStructure(setup, swings, atr);
  if (!trend || !momentum || !volumeP || !structure) {
    return insufficient(["INSUFFICIENT DATA: classification inputs incomplete."]);
  }
  const tfInputs = {};
  const tfList = ["4h", "1h", "15m", "5m"];
  for (const tf of tfList) {
    const data = tf === setupTimeframe ? setup : input.candlesByTf[tf] ?? [];
    if (data.length < TREND_MIN_CANDLES) continue;
    const cl = data.map((c) => c.close);
    const tfAtr = lastAtr(data, 14) ?? 0;
    const t = classifyTrend(
      cl[cl.length - 1],
      lastEma(cl, 20),
      lastEma(cl, 50),
      lastEma(cl, 200),
      tfAtr * 0.05
    );
    if (!t) continue;
    const r = rsiSeries(cl, 14);
    const m = macdSeries(cl);
    const mh = m.map((p) => p.histogram);
    tfInputs[tf] = {
      trend: t.label,
      bullPoints: t.bullPoints,
      bearPoints: t.bearPoints,
      reversalUp: crossedUp(r, 30) || isRising(mh.slice(-4).map((v) => v), 3),
      reversalDown: crossedDown(r, 70) || isFalling(mh.slice(-4).map((v) => v), 3)
    };
  }
  if (!tfInputs[setupTimeframe]) {
    tfInputs[setupTimeframe] = {
      trend: trend.label,
      bullPoints: trend.bullPoints,
      bearPoints: trend.bearPoints,
      reversalUp: momentum.recovering,
      reversalDown: momentum.fading
    };
  }
  const mtf = analyzeMtf(tfInputs);
  const supportDistanceAtr = levels.nearestSupport !== null ? (price - levels.nearestSupport.price) / atr : null;
  const resistanceDistanceAtr = levels.nearestResistance !== null ? (levels.nearestResistance.price - price) / atr : null;
  const bounce = detectBounce({
    price,
    atr,
    momentum,
    structure,
    volume: volumeP,
    levels,
    mtf,
    supportDistanceAtr,
    resistanceDistanceAtr
  });
  const scored = calculateSignalScore({
    trendLong: trend.bullPoints / 5,
    trendShort: trend.bearPoints / 5,
    momentumLong: momentum.longScore,
    momentumShort: momentum.shortScore,
    volume: volumeP.score,
    structureLong: structure.longScore,
    structureShort: structure.shortScore,
    mtfLong: mtf.longScore,
    mtfShort: mtf.shortScore
  });
  const reasons = [...scored.reasons, ...mtf.warnings.map((w) => `MTF: ${w}`)];
  const warnings = [...scored.warnings, ...bounce.bounceWarnings];
  let direction = scored.direction;
  if (direction !== "WAIT" && structure.label === "RANGE" && !structure.brokeAbove && !structure.brokeBelow && trend.label === "NEUTRAL") {
    direction = "WAIT";
    warnings.push("Ranging market, no breakout, neutral trend \u2014 WAIT. Never force a trade.");
  }
  const er = efficiencyRatio(closes);
  if (direction !== "WAIT" && er !== null && er < CHOP_ER_THRESHOLD && !(structure.brokeAbove && structure.retestHeldAbove) && !(structure.brokeBelow && structure.retestHeldBelow)) {
    direction = "WAIT";
    warnings.push(
      `Choppy regime (efficiency ${er.toFixed(2)}) with no held breakout \u2014 WAIT.`
    );
  }
  let entryLow = null;
  let entryHigh = null;
  let invalidation = null;
  let tp1 = null;
  let tp2 = null;
  let tp3 = null;
  let riskReward = null;
  if (direction === "LONG" || direction === "SHORT") {
    if (bounce.direction !== null && bounce.direction !== direction) {
      warnings.push(
        `Bounce detector favors ${bounce.direction} (score ${bounce.bounceScore}) \u2014 conflicts with ${direction} confluence.`
      );
    }
    const plan = buildTradePlan({
      direction,
      price,
      atr,
      levels,
      structure
    });
    if (!plan) {
      direction = "WAIT";
      warnings.push("No valid trade structure (levels/invalidation) \u2014 WAIT. Never force a trade.");
    } else {
      const entryMid = (plan.entryLow + plan.entryHigh) / 2;
      const stopDist = direction === "LONG" ? entryMid - plan.invalidation : plan.invalidation - entryMid;
      const riskAtr = stopDist / atr;
      const refLevel = direction === "LONG" ? levels.nearestSupport?.price ?? structure.lastSwingLow : levels.nearestResistance?.price ?? structure.lastSwingHigh;
      const extensionAtr = refLevel !== null && refLevel !== void 0 ? Math.abs(price - refLevel) / atr : 0;
      if (extensionAtr > MAX_EXTENSION_ATR) {
        direction = "WAIT";
        warnings.push(
          `WAIT \u2014 POOR RISK/REWARD (chasing: price ${extensionAtr.toFixed(1)} ATR from the level).`
        );
      } else if (plan.riskReward < MIN_RISK_REWARD || riskAtr > MAX_RISK_ATR) {
        direction = "WAIT";
        warnings.push(
          `WAIT \u2014 POOR RISK/REWARD (R:R ${plan.riskReward}, stop ${riskAtr.toFixed(1)} ATR).`
        );
      } else {
        entryLow = plan.entryLow;
        entryHigh = plan.entryHigh;
        invalidation = plan.invalidation;
        tp1 = plan.tp1;
        tp2 = plan.tp2;
        tp3 = plan.tp3;
        riskReward = plan.riskReward;
      }
    }
  } else {
    reasons.push(...bounce.bounceReasons);
  }
  return {
    status: "OK",
    signal: {
      symbol,
      timestamp: now,
      timeframe: setupTimeframe,
      direction,
      signalStrength: scored.score,
      classification: direction === "WAIT" ? "WAIT" : scored.classification,
      entryLow,
      entryHigh,
      invalidation,
      tp1,
      tp2,
      tp3,
      riskReward,
      trend: trend.label,
      momentum: momentum.label,
      rsi: rsiNow,
      volume: volumeP.label,
      marketStructure: structure.label,
      brokeAbove: structure.brokeAbove,
      brokeBelow: structure.brokeBelow,
      retestHeld: structure.retestHeldAbove || structure.retestHeldBelow,
      riskAtr: entryLow !== null && invalidation !== null && direction !== "WAIT" ? Math.abs((entryLow + (entryHigh ?? entryLow)) / 2 - invalidation) / atr : null,
      atrPct: Math.round(atr / price * 1e4) / 100,
      falseBreakout: direction === "LONG" ? structure.falseBreakoutUp : structure.falseBreakoutDown,
      multiTimeframe: mtf,
      components: scored.components,
      bounce,
      reasons,
      warnings,
      dataTimestamp,
      longScore: scored.longScore,
      shortScore: scored.shortScore
    }
  };
}

// src/signals/setupType.ts
function classifySetupType(signal) {
  if (signal.direction === "WAIT") return "RANGE";
  const bounceDir = signal.bounce?.direction;
  if (bounceDir !== null && bounceDir !== void 0 && bounceDir === signal.direction && (signal.bounce?.bounceScore ?? 0) >= 60) {
    return "BOUNCE";
  }
  if (signal.direction === "LONG" && signal.brokeAbove) {
    return signal.volume === "LOW" ? "TREND" : "BREAKOUT";
  }
  if (signal.direction === "SHORT" && signal.brokeBelow) {
    return signal.volume === "LOW" ? "TREND" : "BREAKDOWN";
  }
  const mtf15 = signal.multiTimeframe?.tfs.find((t) => t.timeframe === "15m")?.flavor;
  const mtf5 = signal.multiTimeframe?.tfs.find((t) => t.timeframe === "5m")?.flavor;
  if (mtf15 === "PULLBACK" || mtf15 === "BEAR_RALLY") return "PULLBACK";
  if (mtf5 === "BULLISH_REVERSAL" || mtf5 === "BEARISH_REVERSAL" || mtf15 === "BULLISH_REVERSAL" || mtf15 === "BEARISH_REVERSAL") {
    return "REVERSAL";
  }
  if (signal.direction === "LONG") {
    return signal.marketStructure === "BULLISH" ? "TREND" : "RANGE";
  }
  return signal.marketStructure === "BEARISH" ? "TREND" : "RANGE";
}
function stableSignalId(args) {
  return [args.symbol.toUpperCase(), args.direction, args.timeframe, args.setupType, args.anchorTimestamp].join("|");
}
function signalIdFor(signal, setupType) {
  if (signal.direction !== "LONG" && signal.direction !== "SHORT") return null;
  return stableSignalId({
    symbol: signal.symbol,
    direction: signal.direction,
    timeframe: signal.timeframe,
    setupType,
    anchorTimestamp: signal.dataTimestamp
  });
}

// src/scanner/eligibility.ts
function applyEligibility(markets, config) {
  const excluded = [];
  const candidates = markets.filter((m) => {
    if ((m.dayVolumeNotional ?? 0) < config.minVolumeNotional) {
      excluded.push({ symbol: m.symbol, reason: `24h volume below $${config.minVolumeNotional.toLocaleString()}` });
      return false;
    }
    return true;
  });
  candidates.sort((a, b) => (b.dayVolumeNotional ?? 0) - (a.dayVolumeNotional ?? 0));
  const eligible = candidates.slice(0, config.universeSize);
  for (const m of candidates.slice(config.universeSize)) {
    excluded.push({ symbol: m.symbol, reason: `outside top-${config.universeSize} by volume` });
  }
  return { eligible, excluded };
}

// src/scanner/engine.ts
var SCAN_TIMEFRAMES = ["4h", "1h", "15m", "5m"];
var DEFAULT_CONCURRENCY = 6;
async function boundedAll(tasks, limit) {
  const out = new Array(tasks.length);
  let next = 0;
  async function worker() {
    while (next < tasks.length) {
      const i = next++;
      out[i] = await tasks[i]();
    }
  }
  await Promise.all(
    Array.from({ length: Math.min(limit, tasks.length) }, () => worker())
  );
  return out;
}
function messageOf(err) {
  return err instanceof Error && err.message ? err.message : "Unknown scan error.";
}
async function runFullScan(markets, opts) {
  const startedAt = Date.now();
  const { eligible, excluded } = applyEligibility(markets, opts.eligibility);
  const allExcluded = [...excluded];
  const results = [];
  let done = 0;
  let fatalError = null;
  const abort = opts.signal;
  if (abort?.aborted) {
    return emptySummary(opts.setupTimeframe, startedAt, "Scan cancelled.", allExcluded);
  }
  try {
    await boundedAll(
      eligible.map((market) => async () => {
        if (abort?.aborted) return;
        try {
          const data = {};
          const rows = await boundedAll(
            SCAN_TIMEFRAMES.map((tf) => async () => {
              const w = getCandleWindow(tf, Date.now(), 300);
              const res = await getCachedCandles(market.symbol, tf, w.startTime, w.endTime);
              return { tf, candles: res.candles };
            }),
            2
          );
          for (const r of rows) data[r.tf] = r.candles;
          const setup = data[opts.setupTimeframe] ?? [];
          if (setup.length < SETUP_MIN_CANDLES) {
            allExcluded.push({
              symbol: market.symbol,
              reason: `only ${setup.length}/${SETUP_MIN_CANDLES} ${opts.setupTimeframe} candles`
            });
            return;
          }
          const { signal } = buildSignal({
            symbol: market.symbol,
            setupTimeframe: opts.setupTimeframe,
            candlesByTf: data
          });
          const setupType = classifySetupType(signal);
          results.push({
            symbol: market.symbol,
            signal,
            setupType,
            quality: assessQuality(signal),
            id: signalIdFor(signal, setupType)
          });
        } catch (err) {
          allExcluded.push({ symbol: market.symbol, reason: messageOf(err) });
        } finally {
          done += 1;
          opts.onProgress?.(done, eligible.length);
        }
      }),
      opts.concurrency ?? DEFAULT_CONCURRENCY
    );
  } catch (err) {
    fatalError = messageOf(err);
  }
  const completedAt = Date.now();
  if (fatalError && results.length === 0) {
    return {
      status: "ERROR",
      startedAt,
      completedAt,
      setupTimeframe: opts.setupTimeframe,
      results: [],
      scanned: 0,
      excluded: allExcluded,
      error: fatalError,
      breadth: { bullishPct: 0, bearishPct: 0, neutralPct: 0, counted: 0 }
    };
  }
  return {
    status: "COMPLETE",
    startedAt,
    completedAt,
    setupTimeframe: opts.setupTimeframe,
    results: results.sort((a, b) => b.signal.signalStrength - a.signal.signalStrength),
    scanned: results.length,
    excluded: allExcluded,
    error: fatalError,
    breadth: computeBreadth(results)
  };
}
function emptySummary(setupTimeframe, startedAt, error, excluded) {
  return {
    status: "ERROR",
    startedAt,
    completedAt: Date.now(),
    setupTimeframe,
    results: [],
    scanned: 0,
    excluded,
    error,
    breadth: { bullishPct: 0, bearishPct: 0, neutralPct: 0, counted: 0 }
  };
}
function computeBreadth(results) {
  const counted = results.length;
  if (counted === 0) return { bullishPct: 0, bearishPct: 0, neutralPct: 0, counted: 0 };
  const bull = results.filter((r) => r.signal.direction === "LONG").length;
  const bear = results.filter((r) => r.signal.direction === "SHORT").length;
  const pct = (n) => Math.round(n / counted * 1e3) / 10;
  return { bullishPct: pct(bull), bearishPct: pct(bear), neutralPct: pct(counted - bull - bear), counted };
}
function rankSetups(results) {
  return [...results].sort((a, b) => {
    const aDir = a.signal.direction === "WAIT" ? 1 : 0;
    const bDir = b.signal.direction === "WAIT" ? 1 : 0;
    if (aDir !== bDir) return aDir - bDir;
    return b.signal.signalStrength - a.signal.signalStrength;
  });
}

// src/market/classify.ts
function baseSymbol(symbol) {
  const i = symbol.indexOf(":");
  return (i >= 0 ? symbol.slice(i + 1) : symbol).toUpperCase();
}
var COMMODITIES = /* @__PURE__ */ new Set([
  // Metals
  "GOLD",
  "SILVER",
  "COPPER",
  "PLATINUM",
  "PALLADIUM",
  "ALUMINIUM",
  "URANIUM",
  // Energy
  "OIL",
  "BRENT",
  "BRENTOIL",
  "WTI",
  "CL",
  "USOIL",
  "NATGAS",
  "TTF",
  // Agriculturals
  "WHEAT",
  "CORN"
]);
var NON_EQUITY = /* @__PURE__ */ new Set([
  // Indices / ETFs / baskets
  "SP500",
  "USA500",
  "US500",
  "SMALL2000",
  "USTECH",
  "NIFTY",
  "JP225",
  "KR200",
  "EWJ",
  "EWT",
  "EWY",
  "EWZ",
  "XLE",
  "SMH",
  "SEMI",
  "MAG7",
  "SEMIS",
  "ROBOT",
  "INFOTECH",
  "NUCLEAR",
  "DEFENSE",
  "ENERGY",
  "BIOTECH",
  "XYZ100",
  // Forex / rates
  "EUR",
  "GBP",
  "JPY",
  "KRW",
  "DXY",
  "USBOND",
  // Volatility
  "VIX",
  "VOL",
  // Crypto baskets
  "TOTAL2",
  "OTHERS",
  "BTCD",
  // Ambiguous — could be commodity, equity, or crypto token
  "GAS",
  "URNM",
  "DRAM",
  "GOLDJM",
  "SILVERJM"
]);
function classifyMarket(symbol, mainDexSymbols2) {
  const upper = symbol.toUpperCase();
  if (!upper.includes(":")) return "crypto";
  const base = baseSymbol(symbol);
  if (mainDexSymbols2.has(base)) return "crypto";
  if (COMMODITIES.has(base)) return "commodities";
  if (NON_EQUITY.has(base)) return "other";
  return "stocks";
}

// src/cron/universe.ts
function mainDexSymbols(markets) {
  return new Set(
    markets.filter((m) => !m.symbol.includes(":")).map((m) => m.symbol.toUpperCase())
  );
}

// src/cron/manualScan.ts
var DEFAULT_SCAN_LIMIT = 10;
var MAX_SCAN_LIMIT = 20;
var MANUAL_TRADE_MIN_STRENGTH = 70;
var WATCH_MIN_STRENGTH = 60;
var MAX_WATCH = 3;
var SCAN_BUSY_MESSAGE = "\u{1F50E} A manual scan is already running for this chat. Please wait for it to finish, then try again.";
var SCAN_FAILED_MESSAGE = "\u26A0\uFE0F MARKET SCAN FAILED\n\nUnable to retrieve fresh market data right now.\n\nPlease try again shortly.";
var SCAN_UNAUTHORIZED_MESSAGE = "\u{1F512} Telegram is not connected to a CryptoIn account.\n\nOpen CryptoIn and connect Telegram first.";
function parseScanArgs(raw) {
  const tokens = raw.trim().toLowerCase().split(/\s+/).filter(Boolean);
  let category = null;
  let direction = "ALL";
  let tradeOnly = false;
  let limit = DEFAULT_SCAN_LIMIT;
  for (const t of tokens) {
    if (t === "crypto" || t === "stocks" || t === "commodities") {
      category = t;
    } else if (t === "long") {
      direction = "LONG";
    } else if (t === "short") {
      direction = "SHORT";
    } else if (t === "trade" || t === "trades") {
      tradeOnly = true;
    } else if (/^\d+$/.test(t)) {
      const n = Number.parseInt(t, 10);
      if (Number.isFinite(n)) limit = Math.min(MAX_SCAN_LIMIT, Math.max(1, n));
    }
  }
  return {
    categories: category ? [category] : ["crypto", "stocks", "commodities"],
    direction,
    tradeOnly,
    limit
  };
}
var ManualScanError = class extends Error {
  code;
  constructor(message) {
    super(message);
    this.code = "markets-unavailable";
  }
};
async function runManualMarketScan(deps, req) {
  const log = deps.log ?? (() => {
  });
  let markets;
  try {
    const discovered = await deps.listMarkets();
    markets = discovered.markets;
  } catch (err) {
    throw new ManualScanError(err instanceof Error && err.message ? err.message : "Market discovery failed.");
  }
  if (markets.length === 0) {
    throw new ManualScanError("Market discovery returned no markets.");
  }
  const main = mainDexSymbols(markets);
  const failures = [];
  const perCategory = [];
  const all = [];
  let aborted = false;
  for (const category of req.categories) {
    if (deps.signal?.aborted) {
      aborted = true;
      break;
    }
    const universe = markets.filter((m) => classifyMarket(m.symbol, main) === category);
    const counts = {
      category,
      universe: universe.length,
      scanned: 0,
      skipped: 0,
      longs: 0,
      shorts: 0
    };
    if (universe.length === 0) {
      log(`manual-scan: ${category}: no markets listed, skipped`);
      perCategory.push(counts);
      continue;
    }
    try {
      const summary = await deps.scanCategory(universe, category);
      counts.scanned = summary.scanned;
      counts.skipped = summary.excluded.length;
      for (const r of summary.results) {
        if (r.signal.direction === "LONG") counts.longs += 1;
        else if (r.signal.direction === "SHORT") counts.shorts += 1;
      }
      all.push(...summary.results);
      log(
        `manual-scan: ${category}: universe=${counts.universe} scanned=${counts.scanned} skipped=${counts.skipped} longs=${counts.longs} shorts=${counts.shorts}`
      );
    } catch (err) {
      const msg = err instanceof Error && err.message ? err.message : "unknown scan error";
      failures.push(`${category}: ${msg}`);
      log(`manual-scan: ${category}: ERROR ${msg}`);
    }
    perCategory.push(counts);
  }
  if (all.length === 0) {
    throw new ManualScanError(
      failures.length > 0 ? failures.join("; ") : "No markets could be scanned."
    );
  }
  let pool = all;
  if (req.direction !== "ALL") pool = pool.filter((r) => r.signal.direction === req.direction);
  if (req.tradeOnly) {
    pool = pool.filter(
      (r) => r.signal.direction !== "WAIT" && r.signal.signalStrength >= MANUAL_TRADE_MIN_STRENGTH
    );
  }
  const candidates = rankSetups(pool).slice(0, req.limit);
  const watch = !req.tradeOnly && req.direction === "ALL" ? [...all].filter((r) => r.signal.direction === "WAIT" && r.signal.signalStrength >= WATCH_MIN_STRENGTH).sort((a, b) => b.signal.signalStrength - a.signal.signalStrength).slice(0, MAX_WATCH) : [];
  return {
    request: req,
    generatedAt: deps.now,
    marketsDiscovered: markets.length,
    perCategory,
    candidates,
    poolSize: pool.length,
    watch,
    totalLongs: all.filter((r) => r.signal.direction === "LONG").length,
    totalShorts: all.filter((r) => r.signal.direction === "SHORT").length,
    failures: aborted ? [...failures, "scan deadline reached \u2014 showing completed categories"] : failures,
    partial: failures.length > 0 || aborted
  };
}
async function verifyScanAccess(lookup, chatId) {
  const conn = await lookup(chatId);
  if (!conn.paired) return { ok: false, reason: "unpaired" };
  if (!conn.enabled) return { ok: false, reason: "paused" };
  return { ok: true, reason: null };
}
function fmtMoney(v) {
  if (typeof v !== "number" || !Number.isFinite(v)) return "\u2014";
  return `$${v.toLocaleString("en-US", { maximumFractionDigits: v >= 100 ? 2 : 4 })}`;
}
function fmtTimeUTC(ms) {
  if (!Number.isFinite(ms) || ms <= 0) return "\u2014";
  return `${new Date(ms).toISOString().slice(11, 16)} UTC`;
}
function catTitle(c) {
  return c === "crypto" ? "CRYPTO" : c === "stocks" ? "STOCKS" : "COMMODITIES";
}
function formatCandidate(r) {
  const s = r.signal;
  const emoji = s.direction === "LONG" ? "\u{1F7E2}" : "\u{1F534}";
  const entry = s.entryLow !== null && s.entryHigh !== null ? `${fmtMoney(s.entryLow)} \u2013 ${fmtMoney(s.entryHigh)}` : fmtMoney(s.entryLow);
  const reasons = s.reasons.length > 0 ? s.reasons.slice(0, 4) : ["(engine gave no detailed reasons)"];
  return [
    `${emoji} ${s.direction} \u2014 ${r.symbol}`,
    `Score: ${s.signalStrength}/100`,
    `Entry: ${entry}`,
    `SL: ${fmtMoney(s.invalidation)}`,
    `TP1: ${fmtMoney(s.tp1)}`,
    `TP2: ${fmtMoney(s.tp2)}`,
    `R:R: ${s.riskReward !== null ? s.riskReward : "\u2014"}`,
    "",
    "Reasons:",
    ...reasons.map((x) => `\u2022 ${x}`)
  ];
}
function formatManualScanResult(res) {
  const { request } = res;
  const scanned = res.perCategory.reduce((a, c) => a + c.scanned, 0);
  const skipped = res.perCategory.reduce((a, c) => a + c.skipped, 0);
  const catName = request.categories.length === 3 ? "ALL" : catTitle(request.categories[0]);
  const lines = [
    "\u{1F50E} MARKET SCAN",
    "\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501",
    "",
    `Scanned: ${scanned} markets`,
    ...skipped > 0 ? [`Skipped: ${skipped}`] : [],
    `Category: ${catName}`,
    "Timeframe: 15M",
    `Generated: ${fmtTimeUTC(res.generatedAt)}`,
    ...res.partial ? ["", `\u26A0\uFE0F Partial scan: ${res.failures.join("; ")}`] : []
  ];
  if (res.candidates.length === 0) {
    lines.push(
      "",
      request.tradeOnly ? "No qualified trade setups right now." : "No candidates match these filters right now.",
      "",
      `Markets scanned: ${res.marketsDiscovered}`,
      `LONG candidates: ${res.totalLongs}`,
      `SHORT candidates: ${res.totalShorts}`,
      "",
      request.tradeOnly ? "The market conditions currently do not meet the configured signal threshold." : "Try widening the filters (e.g. /scan without direction)."
    );
    return lines.join("\n");
  }
  for (const r of res.candidates) {
    lines.push("", "\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501", "", ...formatCandidate(r));
  }
  if (res.watch.length > 0) {
    lines.push("", "\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501", "", "\u23F3 WATCH", "");
    for (const w of res.watch) {
      lines.push(`${w.symbol} \u2014 ${w.signal.signalStrength}/100`);
      lines.push(`${w.setupType} \xB7 ${w.signal.classification}`);
      lines.push("");
    }
  }
  lines.push("\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501", "");
  lines.push(`Showing top ${res.candidates.length} of ${Math.max(res.poolSize, res.candidates.length)} candidates.`);
  return lines.join("\n").trimEnd();
}

// supabase/functions/_shared/commands.ts
function splitMessage(text, max = 3500) {
  if (text.length <= max) return [text];
  const lines = text.split("\n");
  const chunks = [];
  let cur = "";
  for (const line of lines) {
    const next = cur === "" ? line : `${cur}
${line}`;
    if (next.length > max && cur !== "") {
      chunks.push(cur);
      cur = line;
    } else {
      cur = next;
    }
  }
  if (cur !== "") chunks.push(cur);
  return chunks.length > 0 ? chunks : [text.slice(0, max)];
}

// supabase/functions/telegram-scan/handler.src.ts
var SCAN_DEADLINE_MS = 14e4;
var MAX_CHUNKS = 6;
function globals() {
  return globalThis;
}
function json(status, body) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" }
  });
}
async function botCall(botToken, method, payload) {
  try {
    const res = await fetch(`https://api.telegram.org/bot${botToken}/${method}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
      signal: AbortSignal.timeout(15e3)
    });
    return res.ok;
  } catch {
    return false;
  }
}
async function dbGet(supabaseUrl, serviceKey, path) {
  try {
    const res = await fetch(`${supabaseUrl}/rest/v1/${path}`, {
      headers: { apikey: serviceKey, Authorization: `Bearer ${serviceKey}` },
      signal: AbortSignal.timeout(1e4)
    });
    let body = null;
    try {
      body = await res.json();
    } catch {
    }
    return { status: res.status, json: body };
  } catch {
    return { status: 0, json: null };
  }
}
async function handleScan(env, invoke) {
  const chat = typeof invoke.chat_id === "string" ? invoke.chat_id : "";
  const args = typeof invoke.args === "string" ? invoke.args : "";
  const ackId = typeof invoke.ack_message_id === "number" ? invoke.ack_message_id : null;
  if (chat === "") return;
  const lookup = async (chatId) => {
    const r = await dbGet(
      env.supabaseUrl,
      env.serviceKey,
      `telegram_connections?telegram_chat_id=eq.${encodeURIComponent(chatId)}&select=user_id,enabled`
    );
    const row = r.status === 200 && Array.isArray(r.json) && r.json.length > 0 ? r.json[0] : null;
    return { paired: row !== null, enabled: row?.enabled === true };
  };
  const access = await verifyScanAccess(lookup, chat).catch(() => ({ ok: false, reason: "unpaired" }));
  if (!access.ok) {
    const text = access.reason === "paused" ? "\u23F8\uFE0F Notifications are paused for this chat. Reconnect from the website (Settings \u2192 Telegram) to resume." : SCAN_UNAUTHORIZED_MESSAGE;
    if (ackId !== null) {
      await botCall(env.botToken, "editMessageText", { chat_id: chat, message_id: ackId, text: text.slice(0, 3500) });
    } else {
      await botCall(env.botToken, "sendMessage", { chat_id: chat, text: text.slice(0, 3500) });
    }
    return;
  }
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), SCAN_DEADLINE_MS);
  try {
    const request = parseScanArgs(args);
    const result = await runManualMarketScan(
      {
        now: Date.now(),
        listMarkets: () => getMarkets({ bypassCache: true, signal: ctrl.signal }),
        scanCategory: (universe, _category) => runFullScan(universe, {
          eligibility: { minVolumeNotional: 25e4, universeSize: 60 },
          setupTimeframe: "15m",
          concurrency: 5,
          signal: ctrl.signal
        }),
        signal: ctrl.signal
      },
      request
    );
    const chunks = splitMessage(formatManualScanResult(result)).slice(0, MAX_CHUNKS);
    if (chunks.length === 0) return;
    if (ackId !== null) {
      await botCall(env.botToken, "editMessageText", {
        chat_id: chat,
        message_id: ackId,
        text: chunks[0].slice(0, 3500)
      });
      for (const rest of chunks.slice(1)) {
        await botCall(env.botToken, "sendMessage", { chat_id: chat, text: rest.slice(0, 3500) });
      }
    } else {
      for (const chunk of chunks) {
        await botCall(env.botToken, "sendMessage", { chat_id: chat, text: chunk.slice(0, 3500) });
      }
    }
  } catch {
    const text = SCAN_FAILED_MESSAGE;
    if (ackId !== null) {
      await botCall(env.botToken, "editMessageText", { chat_id: chat, message_id: ackId, text });
    } else {
      await botCall(env.botToken, "sendMessage", { chat_id: chat, text });
    }
  } finally {
    clearTimeout(timer);
  }
}
async function serve(req) {
  const g = globals();
  const supabaseUrl = g.Deno?.env.get("SUPABASE_URL") ?? "";
  const serviceKey = g.Deno?.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
  const botToken = g.Deno?.env.get("TELEGRAM_BOT_TOKEN") ?? "";
  if (supabaseUrl === "" || serviceKey === "" || botToken === "") {
    return json(500, { ok: false, error: "scan service not configured" });
  }
  if (req.method !== "POST") return json(405, { ok: false });
  const auth = req.headers.get("authorization") ?? "";
  if (auth !== `Bearer ${serviceKey}`) {
    return json(401, { ok: false });
  }
  let invoke;
  try {
    invoke = await req.json();
  } catch {
    return json(400, { ok: false });
  }
  const chat = typeof invoke.chat_id === "string" ? invoke.chat_id : "";
  if (chat === "") return json(400, { ok: false });
  if (running.has(chat)) {
    await botCall(botToken, "sendMessage", { chat_id: chat, text: SCAN_BUSY_MESSAGE });
    return json(202, { ok: true, accepted: false, reason: "busy" });
  }
  running.add(chat);
  const env = { supabaseUrl, serviceKey, botToken };
  const done = handleScan(env, invoke).finally(() => running.delete(chat));
  const runtime = g.EdgeRuntime;
  if (runtime && typeof runtime.waitUntil === "function") {
    runtime.waitUntil(done);
  } else {
    await done;
  }
  return json(202, { ok: true, accepted: true });
}
var running = /* @__PURE__ */ new Set();
var deno = globals().Deno;
if (deno && typeof deno.serve === "function") {
  deno.serve(serve);
}
export {
  formatManualScanResult,
  handleScan,
  parseScanArgs,
  runManualMarketScan,
  running,
  serve
};
